//! sRGB and linear light (ft-yccm0.4.7.3).
//!
//! Metal frames render into `BGRA8Unorm_sRGB` targets, as the WebGpu
//! renderer renders into sRGB surfaces. The shaders write linear light, the
//! GPU blends in linear light, and the target stores sRGB-encoded bytes. So
//! an anti-aliased glyph edge, a translucent tint or a cursor blends exactly
//! as it does on the WebGpu path.
//!
//! Colors reach the renderer sRGB-encoded: palette bytes in cells and glyph
//! instances, premultiplied components in the uniforms and clear colors. The
//! shaders decode the bytes through [`SRGB_TO_LINEAR`], a table built from
//! [`srgb_to_linear`] and compiled into every pipeline
//! ([`shader_prelude`]). Uniform colors are converted on the CPU
//! ([`linear_premultiplied`]). The shaders' CPU references use the same
//! functions, so they match the GPU bit for bit up to its final encode.

use std::sync::LazyLock;

/// An sRGB-encoded component (`0.0..=1.0`) in linear light: the standard
/// transfer function, which the GPU's sRGB texture sampling also applies.
#[must_use]
pub fn srgb_to_linear(component: f32) -> f32 {
    let c = component.clamp(0.0, 1.0);
    if c <= 0.04045 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

/// A linear-light component sRGB-encoded, as an sRGB render target stores
/// it (before rounding to 8 bits).
#[must_use]
pub fn linear_to_srgb(component: f32) -> f32 {
    let c = component.clamp(0.0, 1.0);
    if c <= 0.003_130_8 {
        c * 12.92
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    }
}

/// Every sRGB byte in linear light; the shaders' table.
pub static SRGB_TO_LINEAR: LazyLock<[f32; 256]> = LazyLock::new(|| {
    std::array::from_fn(|byte| srgb_to_linear(u8::try_from(byte).map_or(1.0, f32::from) / 255.0))
});

/// An sRGB byte in linear light.
#[must_use]
pub fn byte_to_linear(byte: u8) -> f32 {
    SRGB_TO_LINEAR[usize::from(byte)]
}

/// A premultiplied sRGB-encoded color in premultiplied linear light: the
/// color is unpremultiplied, decoded and premultiplied again. A fully
/// transparent color stays transparent.
#[must_use]
pub fn linear_premultiplied(color: [f32; 4]) -> [f32; 4] {
    let alpha = color[3].clamp(0.0, 1.0);
    if alpha <= 0.0 {
        return [0.0; 4];
    }
    let channel = |c: f32| srgb_to_linear(c / alpha) * alpha;
    [
        channel(color[0]),
        channel(color[1]),
        channel(color[2]),
        alpha,
    ]
}

/// A premultiplied linear-light color as the `BGRA8Unorm_sRGB` bytes the
/// GPU stores: color components encoded, alpha stored as is, each rounded
/// to the nearest 8-bit value.
#[must_use]
// Clamped to 0.0..=255.0 before the cast.
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
pub fn to_srgb_bgra8(color: [f32; 4]) -> [u8; 4] {
    let byte = |c: f32| (c.clamp(0.0, 1.0) * 255.0).round() as u8;
    [
        byte(linear_to_srgb(color[2])),
        byte(linear_to_srgb(color[1])),
        byte(linear_to_srgb(color[0])),
        byte(color[3]),
    ]
}

/// Stored `BGRA8Unorm_sRGB` bytes in premultiplied linear light, as the
/// GPU reads them back for blending.
#[must_use]
pub fn from_srgb_bgra8(bytes: [u8; 4]) -> [f32; 4] {
    [
        byte_to_linear(bytes[2]),
        byte_to_linear(bytes[1]),
        byte_to_linear(bytes[0]),
        f32::from(bytes[3]) / 255.0,
    ]
}

/// Metal source defining `SRGB_TO_LINEAR`, prepended to every shader the
/// renderer compiles. Each value is written in Rust's shortest round-trip
/// form, so the shader's table holds exactly the CPU's `f32`s.
#[must_use]
pub fn shader_prelude() -> String {
    let values: Vec<String> = SRGB_TO_LINEAR
        .iter()
        .map(|value| format!("{value:?}f"))
        .collect();
    format!(
        "// Generated by src/color.rs: sRGB bytes in linear light.\n\
         constant float SRGB_TO_LINEAR[256] = {{{}}};\n",
        values.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_transfer_functions_invert_each_other_on_every_byte() {
        for byte in 0..=255_u8 {
            let linear = byte_to_linear(byte);
            assert!((0.0..=1.0).contains(&linear));
            let back = (linear_to_srgb(linear) * 255.0).round();
            assert!((back - f32::from(byte)).abs() < f32::EPSILON, "{byte}");
        }
        assert!(byte_to_linear(0).abs() < f32::EPSILON);
        assert!((byte_to_linear(255) - 1.0).abs() < 1e-6);
        // Mid-gray is about a fifth of the light.
        assert!((byte_to_linear(128) - 0.215_860_5).abs() < 1e-6);
    }

    #[test]
    fn premultiplied_colors_are_decoded_unpremultiplied() {
        assert_eq!(linear_premultiplied([0.0, 0.0, 0.0, 0.0]), [0.0; 4]);
        let opaque = linear_premultiplied([0.5, 1.0, 0.0, 1.0]);
        assert!((opaque[0] - srgb_to_linear(0.5)).abs() < 1e-7);
        assert_eq!(&opaque[1..], &[1.0, 0.0, 1.0]);
        // Half-transparent white stays white at half coverage.
        let half = linear_premultiplied([0.5, 0.5, 0.5, 0.5]);
        assert_eq!(half, [0.5, 0.5, 0.5, 0.5]);
        // Half-transparent mid-gray: decode the straight color, then
        // premultiply.
        let gray = linear_premultiplied([0.25, 0.25, 0.25, 0.5]);
        assert!((gray[0] - srgb_to_linear(0.5) * 0.5).abs() < 1e-7);
    }

    #[test]
    fn stored_bytes_round_trip_through_linear_light() {
        for bytes in [[0, 0, 0, 255], [30, 42, 200, 255], [255, 128, 1, 128]] {
            assert_eq!(to_srgb_bgra8(from_srgb_bgra8(bytes)), bytes);
        }
    }

    #[test]
    fn the_shader_prelude_holds_the_cpu_table_exactly() {
        let prelude = shader_prelude();
        let start = prelude.find('{').expect("a table") + 1;
        let end = prelude.rfind('}').expect("a table");
        let parsed: Vec<f32> = prelude[start..end]
            .split(", ")
            .map(|value| value.trim_end_matches('f').parse().expect("a float"))
            .collect();
        assert_eq!(parsed.len(), 256);
        for (byte, value) in parsed.iter().enumerate() {
            assert_eq!(value.to_bits(), SRGB_TO_LINEAR[byte].to_bits(), "{byte}");
        }
    }
}
