//! Allow-list for the cx-propagation lint.
//!
//! Two kinds of carve-outs, both load-bearing.
//!
//! 1. [`EXEMPT_FILES`] — runtime-layer modules that *are* the seal.
//!    They define `Cx` and `RuntimeProof` themselves; requiring them
//!    to take a `Cx` parameter is circular.
//!
//! 2. [`WRAPPER_EXEMPTIONS`] — ergonomic wrappers around a `_with_cx`
//!    sibling. The wrapper constructs a default `Cx` internally and
//!    delegates. Each entry must be paired with a real covered
//!    sibling on the same file (the analyzer enforces this — a stale
//!    wrapper exemption is a lint failure).
//!
//! The two lists are kept in sync with the Python audit script at
//! `scripts/check_runtime_proof_coverage.py`. They share a single
//! source of truth: `docs/runtime/cx-propagation-lint.md` documents
//! the decision tree for adding entries.
//!
//! # Adding a new exemption
//!
//! 1. Confirm the function is genuinely a wrapper (constructs a
//!    default `Cx`, delegates to a covered sibling) — *not* an
//!    "I haven't gotten around to threading Cx yet" placeholder.
//! 2. Add a comment in the source explaining why the wrapper is
//!    safe to exempt.
//! 3. Add an entry here AND in `scripts/check_runtime_proof_coverage.py`.
//!    The two lists must stay in lockstep; CI guards against drift.
//!    The drift guard lives at `scripts/cx_propagation_lockstep.py`
//!    (filed as ft-jbsbx).

/// Runtime-layer modules that *are* the seal. They cannot take a
/// `Cx` parameter on themselves without circular dependency. Add
/// sparingly — every entry is permanent doctrine.
pub const EXEMPT_FILES: &[&str] = &[
    "runtime_async.rs", // wrapper module — primitives sealed elsewhere
    "runtime_proof.rs", // defines the seal itself
    "cx.rs",            // the canonical structured-async witness
    "cx_stub.rs",       // build-time stub of cx.rs (no-op shim)
];

/// Ergonomic wrappers around a `_with_cx` / `_cx` sibling.
///
/// Each entry is a `(relative_path, fn_name)` pair. Paths are
/// rooted at `crates/frankenterm-core/src/` and use forward
/// slashes (matches the Python audit script).
///
/// This list is the **full port** of
/// `scripts/check_runtime_proof_coverage.py::WRAPPER_EXEMPTIONS`
/// (ft-l8bmk). The two lists are kept in lockstep by ft-jbsbx
/// (drift guard filed but not yet wired into CI).
///
/// Generated from the Python source via:
///   python3 -c "import importlib.util; \
///     spec = importlib.util.spec_from_file_location('audit', \
///     'scripts/check_runtime_proof_coverage.py'); \
///     m = importlib.util.module_from_spec(spec); \
///     spec.loader.exec_module(m); \
///     [print(f'    (\"{f}\", \"{n}\"),') \
///       for f, n in sorted(m.WRAPPER_EXEMPTIONS)]"
///
/// Per-entry rationale lives in the Python script's inline
/// comments grouped by source bead (ft-4ku44 ipc.rs / ft-dit9w
/// workflows / ft-7xbaz wezterm.rs / ft-7b8hf storage / ft-haed8
/// long-tail / etc.). Splitting the comments across both files
/// would create drift; the Python file remains the canonical
/// source for the *why* of each exemption.
pub const WRAPPER_EXEMPTIONS: &[(&str, &str)] = &[
    ("alerts.rs", "check_alerts"),
    ("approval.rs", "attach_to_decision"),
    ("approval.rs", "consume"),
    ("approval.rs", "consume_for_plan"),
    ("approval.rs", "consume_for_plan_with_context"),
    ("approval.rs", "consume_with_context"),
    ("approval.rs", "issue"),
    ("approval.rs", "issue_for_plan"),
    ("cancellation_safe_channel.rs", "recv"),
    ("cancellation_safe_channel.rs", "reserve"),
    ("cass.rs", "export_content"),
    ("cass.rs", "export_sessions"),
    ("cass.rs", "query"),
    ("cass.rs", "query_session"),
    ("cass.rs", "search"),
    ("cass.rs", "search_sessions"),
    ("cass.rs", "status"),
    ("cass.rs", "trigger_index"),
    ("caut.rs", "refresh"),
    ("caut.rs", "usage"),
    ("cleanup.rs", "cleanup_apply"),
    ("cleanup.rs", "cleanup_preview"),
    ("cpu_pressure.rs", "run"),
    ("diagnostic.rs", "generate_bundle"),
    ("environment.rs", "detect"),
    ("event_stream.rs", "next"),
    ("event_stream.rs", "wait"),
    ("events.rs", "recv"),
    ("export.rs", "export_jsonl"),
    ("ingest.rs", "persist_captured_segment"),
    ("ipc.rs", "bind"),
    ("ipc.rs", "bind_with_permissions"),
    ("ipc.rs", "call_rpc"),
    ("ipc.rs", "clear_pane_priority"),
    ("ipc.rs", "pane_state"),
    ("ipc.rs", "ping"),
    ("ipc.rs", "run"),
    ("ipc.rs", "run_with_auth"),
    ("ipc.rs", "run_with_registry"),
    ("ipc.rs", "run_with_registry_and_auth"),
    ("ipc.rs", "run_with_registry_auth_and_rpc"),
    ("ipc.rs", "run_with_registry_auth_rpc_and_search_config"),
    ("ipc.rs", "send_user_var"),
    ("ipc.rs", "set_pane_priority"),
    ("ipc.rs", "status"),
    ("mcp_helpers.rs", "derive_osc_state_from_storage"),
    ("mcp_helpers.rs", "fetch_pane_state_from_ipc"),
    ("mcp_helpers.rs", "record_mcp_audit"),
    ("mcp_helpers.rs", "resolve_pane_capabilities"),
    ("memory_budget.rs", "run"),
    ("memory_pressure.rs", "run"),
    ("metrics.rs", "start"),
    ("metrics.rs", "wait"),
    ("native_events.rs", "bind"),
    ("native_events.rs", "run"),
    ("notifications.rs", "handle_detection"),
    ("orphan_reaper.rs", "reap_orphans"),
    ("orphan_reaper.rs", "run_orphan_reaper"),
    ("policy.rs", "send_control"),
    ("policy.rs", "send_ctrl_c"),
    ("policy.rs", "send_ctrl_d"),
    ("policy.rs", "send_ctrl_z"),
    ("policy.rs", "send_text"),
    ("pool.rs", "acquire"),
    ("pool.rs", "clear"),
    ("pool.rs", "evict_idle"),
    ("pool.rs", "put"),
    ("pool.rs", "stats"),
    ("pool.rs", "try_acquire"),
    ("protocol_recovery.rs", "execute"),
    ("recorder_migration.rs", "m0_preflight"),
    ("recorder_migration.rs", "m2_import"),
    ("recorder_migration.rs", "m3_checkpoint_sync"),
    ("recorder_migration.rs", "m5_cutover"),
    ("recorder_migration.rs", "run_m0_m2"),
    ("recording.rs", "record_event"),
    ("recording.rs", "record_segment"),
    ("recording.rs", "start_recording"),
    ("recording.rs", "stop_recording"),
    ("replay.rs", "play"),
    ("replay.rs", "play_simple"),
    ("reports.rs", "generate_session_report"),
    ("restore_layout.rs", "restore"),
    ("restore_process.rs", "execute"),
    ("restore_scrollback.rs", "inject"),
    ("retry.rs", "with_retry"),
    ("retry.rs", "with_retry_and_circuit"),
    ("retry.rs", "with_retry_outcome"),
    ("retry.rs", "with_smart_retry"),
    ("robot_sdk_contracts.rs", "call"),
    ("robot_sdk_contracts.rs", "call_value"),
    ("runtime.rs", "join"),
    ("runtime.rs", "shutdown"),
    ("runtime.rs", "shutdown_with_summary"),
    ("runtime.rs", "start"),
    ("runtime.rs", "update_health_snapshot"),
    ("runtime.rs", "write_queue_depth"),
    ("search_bridge.rs", "cancelled"),
    ("search_bridge.rs", "search"),
    ("search_explain.rs", "build_explain_context"),
    ("secrets.rs", "scan_storage"),
    ("secrets.rs", "scan_storage_incremental"),
    ("session_correlation.rs", "correlate_and_persist_for_pane"),
    ("session_correlation.rs", "correlate_with_cass"),
    ("session_correlation.rs", "refresh_cass_summary_for_session"),
    ("session_restore.rs", "detect_and_restore"),
    ("session_restore.rs", "restore"),
    ("session_retention.rs", "cleanup_sessions_async"),
    ("sharding.rs", "list_all_panes"),
    ("sharding.rs", "shard_health_report"),
    ("sharding.rs", "shard_watchdog_warnings"),
    ("sharding.rs", "spawn_with_hints"),
    ("simulation.rs", "check_all_expectations"),
    ("simulation.rs", "check_expectation"),
    ("simulation.rs", "execute_all"),
    ("simulation.rs", "execute_all_with_resize_timeline"),
    ("simulation.rs", "execute_until"),
    ("simulation.rs", "execute_until_with_resize_timeline"),
    ("simulation.rs", "new"),
    ("simulation.rs", "setup"),
    ("simulation.rs", "trigger_exercise_events"),
    ("simulation.rs", "with_scenario"),
    ("snapshot_engine.rs", "capture"),
    ("snapshot_engine.rs", "cleanup"),
    ("snapshot_engine.rs", "mark_shutdown"),
    ("snapshot_engine.rs", "run_periodic"),
    ("snapshot_engine.rs", "shutdown_checkpoint"),
    ("spsc_ring_buffer.rs", "recv"),
    ("spsc_ring_buffer.rs", "send"),
    ("storage.rs", "acknowledge_notification"),
    ("storage.rs", "add_event_label"),
    ("storage.rs", "aggregate_by_agent"),
    ("storage.rs", "aggregate_daily_metrics"),
    ("storage.rs", "append_segment"),
    ("storage.rs", "checkpoint"),
    ("storage.rs", "consume_approval_token"),
    ("storage.rs", "consume_approval_token_by_code"),
    ("storage.rs", "consume_prepared_plan"),
    ("storage.rs", "count_active_approvals"),
    ("storage.rs", "count_audit_actions_before"),
    ("storage.rs", "count_events_before"),
    ("storage.rs", "count_events_by_tier"),
    ("storage.rs", "count_notification_history_before"),
    ("storage.rs", "count_segments_before"),
    ("storage.rs", "count_unhandled_events_by_pane"),
    ("storage.rs", "count_usage_metrics_before"),
    ("storage.rs", "create_reservation"),
    ("storage.rs", "database_page_stats"),
    ("storage.rs", "delete_account"),
    ("storage.rs", "delete_events_before"),
    ("storage.rs", "delete_events_by_tier"),
    ("storage.rs", "delete_agent_profile"),
    ("storage.rs", "delete_pane_bookmark"),
    ("storage.rs", "delete_saved_search"),
    ("storage.rs", "embedding_stats"),
    ("storage.rs", "expire_stale_reservations"),
    ("storage.rs", "export_gaps"),
    ("storage.rs", "export_reservations"),
    ("storage.rs", "export_segments"),
    ("storage.rs", "export_sessions"),
    ("storage.rs", "export_workflows"),
    ("storage.rs", "find_incomplete_workflows"),
    ("storage.rs", "get_account"),
    ("storage.rs", "get_accounts_by_service"),
    ("storage.rs", "get_action_history"),
    ("storage.rs", "get_action_plan"),
    ("storage.rs", "get_action_undo"),
    ("storage.rs", "get_active_reservation"),
    ("storage.rs", "get_active_sessions"),
    ("storage.rs", "get_agent_profile"),
    ("storage.rs", "get_agent_session"),
    ("storage.rs", "get_approval_token"),
    ("storage.rs", "get_approval_token_by_code"),
    ("storage.rs", "get_audit_actions"),
    ("storage.rs", "get_audit_actions_stream"),
    ("storage.rs", "get_embedding"),
    ("storage.rs", "get_event_annotations"),
    ("storage.rs", "get_event_identity_key"),
    ("storage.rs", "get_events"),
    ("storage.rs", "get_events_stream"),
    ("storage.rs", "get_fts_index_state"),
    ("storage.rs", "get_gaps"),
    ("storage.rs", "get_indexing_health"),
    ("storage.rs", "get_last_activity_by_pane"),
    ("storage.rs", "get_latest_checkpoint_hash"),
    ("storage.rs", "get_latest_step_log"),
    ("storage.rs", "get_max_seq"),
    ("storage.rs", "get_notification"),
    ("storage.rs", "get_pane"),
    ("storage.rs", "get_pane_bookmark_by_alias"),
    ("storage.rs", "get_pane_indexing_stats"),
    ("storage.rs", "get_panes"),
    ("storage.rs", "get_prepared_plan"),
    ("storage.rs", "get_retention_cleanup_count"),
    ("storage.rs", "get_saved_search_by_name"),
    ("storage.rs", "get_segment_time_range"),
    ("storage.rs", "get_segments"),
    ("storage.rs", "get_sessions_for_pane"),
    ("storage.rs", "get_step_logs"),
    ("storage.rs", "get_timeline"),
    ("storage.rs", "get_unembedded_segments"),
    ("storage.rs", "get_unhandled_events"),
    ("storage.rs", "get_workflow"),
    ("storage.rs", "hybrid_search_with_results"),
    ("storage.rs", "increment_notification_retry"),
    ("storage.rs", "insert_agent_profile"),
    ("storage.rs", "insert_approval_token"),
    ("storage.rs", "insert_mux_session"),
    ("storage.rs", "insert_pane_bookmark"),
    ("storage.rs", "insert_prepared_plan"),
    ("storage.rs", "insert_saved_search"),
    ("storage.rs", "insert_session_checkpoint"),
    ("storage.rs", "insert_step_log"),
    ("storage.rs", "is_writable"),
    ("storage.rs", "latest_secret_scan_report"),
    ("storage.rs", "list_active_reservations"),
    ("storage.rs", "list_agent_profiles"),
    ("storage.rs", "list_pane_bookmarks"),
    ("storage.rs", "list_pane_bookmarks_by_tag"),
    ("storage.rs", "list_saved_searches"),
    ("storage.rs", "mark_action_undone"),
    ("storage.rs", "mark_event_handled"),
    ("storage.rs", "mark_session_shutdown_clean"),
    ("storage.rs", "new"),
    ("storage.rs", "prune_segments_before"),
    ("storage.rs", "prune_session_checkpoints"),
    ("storage.rs", "purge_audit_actions_before"),
    ("storage.rs", "purge_notification_history"),
    ("storage.rs", "purge_usage_metrics"),
    ("storage.rs", "query_notification_history"),
    ("storage.rs", "query_usage_metrics"),
    ("storage.rs", "rebuild_fts"),
    ("storage.rs", "record_audit_action"),
    ("storage.rs", "record_audit_action_redacted"),
    ("storage.rs", "record_event"),
    ("storage.rs", "record_gap"),
    ("storage.rs", "record_maintenance"),
    ("storage.rs", "record_notification"),
    ("storage.rs", "record_policy_denial_audit"),
    ("storage.rs", "record_secret_scan_report"),
    ("storage.rs", "record_usage_metric"),
    ("storage.rs", "record_usage_metrics_batch"),
    ("storage.rs", "release_reservation"),
    ("storage.rs", "remove_event_label"),
    ("storage.rs", "retention_cleanup"),
    ("storage.rs", "scan_segments"),
    ("storage.rs", "search"),
    ("storage.rs", "search_with_options"),
    ("storage.rs", "search_with_results"),
    ("storage.rs", "select_account"),
    ("storage.rs", "semantic_search"),
    ("storage.rs", "set_event_note"),
    ("storage.rs", "set_event_triage_state"),
    ("storage.rs", "shutdown"),
    ("storage.rs", "store_embedding"),
    ("storage.rs", "store_embedding_f32"),
    ("storage.rs", "sync_fts"),
    ("storage.rs", "update_account_last_used"),
    ("storage.rs", "update_notification_status"),
    ("storage.rs", "update_saved_search_run"),
    ("storage.rs", "update_saved_search_schedule"),
    ("storage.rs", "upsert_account"),
    ("storage.rs", "upsert_action_plan"),
    ("storage.rs", "upsert_action_undo"),
    ("storage.rs", "upsert_action_undo_redacted"),
    ("storage.rs", "upsert_agent_session"),
    ("storage.rs", "upsert_pane"),
    ("storage.rs", "upsert_workflow"),
    ("storage.rs", "vacuum"),
    ("storage.rs", "with_config"),
    ("storage/handle/event_mutes.rs", "add_event_mute"),
    ("storage/handle/event_mutes.rs", "is_event_muted"),
    ("storage/handle/event_mutes.rs", "list_active_mutes"),
    ("storage/handle/event_mutes.rs", "remove_event_mute"),
    ("storage_telemetry.rs", "append_batch_instrumented"),
    ("survival.rs", "run"),
    ("tailer.rs", "join_next"),
    ("tailer.rs", "shutdown"),
    ("telemetry.rs", "run"),
    ("ui_query.rs", "list_pane_bookmarks"),
    ("ui_query.rs", "list_saved_searches"),
    ("undo.rs", "execute"),
    ("vendored.rs", "connect"),
    ("vendored/mux_client.rs", "batch"),
    ("vendored/mux_client.rs", "connect"),
    ("vendored/mux_client.rs", "create_floating_pane"),
    ("vendored/mux_client.rs", "cycle_stack"),
    ("vendored/mux_client.rs", "get_lines"),
    ("vendored/mux_client.rs", "get_pane_render_changes"),
    ("vendored/mux_client.rs", "get_pane_render_changes_batch"),
    ("vendored/mux_client.rs", "list_panes"),
    ("vendored/mux_client.rs", "move_floating_pane"),
    ("vendored/mux_client.rs", "next"),
    ("vendored/mux_client.rs", "remove_floating_pane"),
    ("vendored/mux_client.rs", "select_stack_pane"),
    ("vendored/mux_client.rs", "send_paste"),
    ("vendored/mux_client.rs", "set_floating_pane_z"),
    ("vendored/mux_client.rs", "set_layout_cycle"),
    ("vendored/mux_client.rs", "shutdown"),
    ("vendored/mux_client.rs", "swap_to_layout"),
    ("vendored/mux_client.rs", "toggle_floating_pane"),
    ("vendored/mux_client.rs", "update_pane_constraints"),
    ("vendored/mux_client.rs", "write_to_pane"),
    ("vendored/mux_pool.rs", "clear"),
    ("vendored/mux_pool.rs", "evict_idle"),
    ("vendored/mux_pool.rs", "get_lines"),
    ("vendored/mux_pool.rs", "get_pane_render_changes"),
    ("vendored/mux_pool.rs", "get_pane_render_changes_batch"),
    ("vendored/mux_pool.rs", "health_check"),
    ("vendored/mux_pool.rs", "list_panes"),
    ("vendored/mux_pool.rs", "send_paste"),
    ("vendored/mux_pool.rs", "stats"),
    ("vendored/mux_pool.rs", "write_to_pane"),
    ("wait.rs", "wait_for"),
    ("wait.rs", "wait_for_condition"),
    ("wait.rs", "wait_for_condition_with_backoff"),
    ("wait.rs", "wait_for_quiescence"),
    ("wait.rs", "wait_for_quiescence_with_backoff"),
    ("wait.rs", "wait_for_value"),
    ("watchdog.rs", "check"),
    ("watchdog.rs", "join"),
    ("web.rs", "shutdown"),
    ("web/server.rs", "run_web_server"),
    ("web/server.rs", "start_web_server"),
    ("web_framework.rs", "finish"),
    ("web_framework.rs", "start"),
    ("webhook.rs", "dispatch"),
    ("webhook.rs", "dispatch_payload"),
    ("wezterm.rs", "activate_pane"),
    ("wezterm.rs", "add_default_pane"),
    ("wezterm.rs", "add_pane"),
    ("wezterm.rs", "get_pane"),
    ("wezterm.rs", "get_pane_direction"),
    ("wezterm.rs", "get_text"),
    ("wezterm.rs", "inject"),
    ("wezterm.rs", "inject_output"),
    ("wezterm.rs", "kill_pane"),
    ("wezterm.rs", "list_panes"),
    ("wezterm.rs", "pane_count"),
    ("wezterm.rs", "pane_state"),
    ("wezterm.rs", "pane_tiered_scrollback_summary"),
    ("wezterm.rs", "send_control"),
    ("wezterm.rs", "send_ctrl_c"),
    ("wezterm.rs", "send_ctrl_d"),
    ("wezterm.rs", "send_text"),
    ("wezterm.rs", "send_text_no_paste"),
    ("wezterm.rs", "send_text_with_options"),
    ("wezterm.rs", "set_watchdog_warning_error"),
    ("wezterm.rs", "set_watchdog_warnings"),
    ("wezterm.rs", "spawn"),
    ("wezterm.rs", "spawn_targeted"),
    ("wezterm.rs", "split_pane"),
    ("wezterm.rs", "wait_for"),
    ("wezterm.rs", "wait_for_codex_session_summary"),
    ("wezterm.rs", "zoom_pane"),
    ("workflows/account_steps.rs", "mark_account_used"),
    (
        "workflows/account_steps.rs",
        "persist_caut_refresh_accounts",
    ),
    ("workflows/account_steps.rs", "refresh_and_select_account"),
    ("workflows/codex_exit.rs", "codex_exit_and_wait_for_summary"),
    ("workflows/codex_exit.rs", "persist_codex_session_summary"),
    ("workflows/context.rs", "send_ctrl_c"),
    ("workflows/context.rs", "send_ctrl_d"),
    ("workflows/context.rs", "send_ctrl_z"),
    ("workflows/context.rs", "send_text"),
    ("workflows/engine.rs", "fetch_workflow_start_action_id"),
    ("workflows/engine.rs", "find_incomplete"),
    ("workflows/engine.rs", "log_step"),
    ("workflows/engine.rs", "record_workflow_start_action"),
    ("workflows/engine.rs", "record_workflow_step_action"),
    ("workflows/engine.rs", "record_workflow_terminal_action"),
    ("workflows/engine.rs", "resume"),
    ("workflows/engine.rs", "start"),
    ("workflows/engine.rs", "start_with_id"),
    ("workflows/engine.rs", "update_status"),
    ("workflows/plan_helpers.rs", "check_step_idempotency"),
    ("workflows/runner.rs", "abort_execution"),
    ("workflows/runner.rs", "handle_detection"),
    ("workflows/runner.rs", "resume_incomplete"),
    ("workflows/runner.rs", "run"),
    ("workflows/runner.rs", "run_workflow"),
    ("workflows/wait_execution.rs", "execute"),
];
