//! Route discovery generated by the same framework builder as the live router.
//!
//! This first increment describes registered paths and methods, not complete
//! query, response, error or SSE schemas (ft-xxfwy.55.2.2). Keeping generation
//! inside AppBuilder prevents a second route inventory from silently drifting.

use crate::web_framework::OpenApiConfig;

pub(super) fn config() -> OpenApiConfig {
    // Do not enable the framework's optional CDN-backed Swagger/ReDoc pages.
    // The document is served by the existing loopback-only application and
    // inherits its middleware; enabling discovery does not enable remote bind.
    OpenApiConfig::new()
        .title("FrankenTerm observation API")
        .version(crate::VERSION)
        .description(
            "Live read-only route discovery. Query, response, error and SSE schemas are not yet complete. Terminal WebSocket and mutation APIs are not provided by this document.",
        )
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use crate::web::resolve_runtime_limits;

    #[test]
    fn openapi_discovery_matches_live_route_inventory() {
        let app = super::super::router::build_app(None, None, resolve_runtime_limits(None));
        let spec: serde_json::Value = serde_json::from_str(
            app.openapi_spec()
                .expect("production builder must enable route discovery"),
        )
        .expect("framework must generate valid JSON");
        let actual: BTreeSet<_> = app
            .routes()
            .filter(|(_, path)| *path != "/openapi.json")
            .map(|(method, path)| (path.to_owned(), method.as_str().to_ascii_lowercase()))
            .collect();
        let expected: BTreeSet<_> = [
            "/health",
            "/panes",
            "/events",
            "/search",
            "/bookmarks",
            "/ruleset-profile",
            "/saved-searches",
            "/stream/events",
            "/stream/deltas",
        ]
        .into_iter()
        .map(|path| (path.to_owned(), "get".to_owned()))
        .collect();
        assert_eq!(actual, expected, "review missing or newly exposed routes");
        let mut documented = BTreeSet::new();
        let mut operation_ids = BTreeSet::new();
        for (path, item) in spec["paths"].as_object().expect("paths object") {
            for (method, operation) in item.as_object().expect("path item") {
                assert!(documented.insert((path.clone(), method.clone())));
                let id = operation["operationId"]
                    .as_str()
                    .filter(|id| !id.is_empty())
                    .expect("every operation must have a nonempty ID");
                assert!(operation_ids.insert(id), "duplicate operation ID: {id}");
                assert!(operation.get("security").is_none(), "auth is not wired yet");
            }
        }
        assert_eq!(documented, actual, "discovery and live routes must agree");
        assert_eq!(documented.len(), 9, "review newly exposed operations");
        assert!(documented.iter().all(|(_, method)| method == "get"));
        assert_eq!(app.routes().count(), 10, "no external docs UI routes");
        assert_eq!(spec["info"]["title"], "FrankenTerm observation API");
        assert_eq!(spec["info"]["version"], crate::VERSION);
        assert_eq!(spec["openapi"], "3.1.0");
        assert!(spec.get("security").is_none(), "no unwired global auth");
        assert!(spec["components"].get("securitySchemes").is_none());
        assert!(
            spec["info"]["description"]
                .as_str()
                .expect("discovery scope must be explicit")
                .contains("not yet complete")
        );
    }
}
