//! Atlas-packing attestation generator (ft-gtcm9.5).
//!
//! Runs the same four-corpus benchmark as `benches/atlas_packing.rs` but
//! emits a structured JSON summary (per-(corpus, packer) `wasted_pct` +
//! `allocs_total`) instead of criterion timing. The release pipeline
//! invokes this binary to refresh `docs/perf/atlas-packing.json` before
//! `scripts/attestation-build.sh` hashes it into the per-release bundle.
//!
//! Why a separate example rather than reusing the criterion bench:
//! criterion measures iteration time, not packing efficiency, so its
//! `target/criterion/.../estimates.json` does not carry the structural
//! data the attestation needs. This example calls into the same public
//! `frankenterm_core::atlas_bin_packing` surface as the bench and emits
//! the structural data directly.
//!
//! Usage:
//!   cargo run --release --example atlas_packing_attestation \
//!     -p frankenterm-core --no-default-features
//!     > docs/perf/atlas-packing.json

use frankenterm_core::atlas_bin_packing::{
    AllocationOutcome, Atlas2DSize, BinPacker, GlyphSize, PackerKind, PackingStats, make_packer,
};

pub(crate) const ATLAS_SIZE: u32 = 2048;
pub(crate) const SCHEMA_VERSION: &str = "1.0.0";

pub(crate) fn corpus_latin() -> Vec<GlyphSize> {
    (0x20u32..=0x7eu32)
        .map(|cp| GlyphSize::new(8 + (cp % 4), 16))
        .collect()
}

pub(crate) fn corpus_cjk() -> Vec<GlyphSize> {
    (0..1500u32)
        .map(|i| GlyphSize::new(16 + (i % 3), 16 + (i % 3)))
        .collect()
}

pub(crate) fn corpus_nerd_font() -> Vec<GlyphSize> {
    let mut glyphs = corpus_latin();
    glyphs.extend((0..500u32).map(|i| GlyphSize::new(12 + (i % 13), 12 + (i % 13))));
    glyphs
}

pub(crate) fn corpus_emoji() -> Vec<GlyphSize> {
    (0..750u32)
        .map(|i| GlyphSize::new(16 + (i % 5), 16 + (i % 5)))
        .collect()
}

pub(crate) fn corpora() -> Vec<(&'static str, Vec<GlyphSize>)> {
    vec![
        ("latin", corpus_latin()),
        ("cjk", corpus_cjk()),
        ("nerd_font", corpus_nerd_font()),
        ("emoji", corpus_emoji()),
    ]
}

pub(crate) fn pack_into(kind: PackerKind, glyphs: &[GlyphSize]) -> (PackingStats, u64, u64) {
    let size = Atlas2DSize::try_new(ATLAS_SIZE, ATLAS_SIZE).expect("atlas size > 0");
    let mut packer: Box<dyn BinPacker> = make_packer(kind, size);
    let mut stats = PackingStats::default();
    stats.record_atlas_size(size);
    let mut placed_total = 0u64;
    let mut rejected_total = 0u64;
    for glyph in glyphs {
        match packer.try_alloc(*glyph) {
            AllocationOutcome::Placed(rect) => {
                stats.record_placed(rect);
                placed_total += 1;
            }
            AllocationOutcome::Rejected(_) => {
                stats.record_reject();
                rejected_total += 1;
            }
        }
    }
    (stats, placed_total, rejected_total)
}

pub(crate) fn packer_label(kind: PackerKind) -> &'static str {
    match kind {
        PackerKind::Shelf => "shelf",
        PackerKind::Skyline => "skyline",
        PackerKind::MaximalRectangles => "maximal_rectangles",
    }
}

fn main() {
    let mut entries: Vec<String> = Vec::new();
    for (corpus_name, glyphs) in corpora() {
        for kind in [
            PackerKind::Shelf,
            PackerKind::Skyline,
            PackerKind::MaximalRectangles,
        ] {
            let (stats, placed_total, rejected_total) = pack_into(kind, &glyphs);
            entries.push(format!(
                "    {{\n      \"corpus\": \"{corpus}\",\n      \"packer\": \"{packer}\",\n      \"glyphs_total\": {glyphs_total},\n      \"allocs_total\": {placed_total},\n      \"rejects_total\": {rejected_total},\n      \"used_bytes\": {used_bytes},\n      \"atlas_bytes\": {atlas_bytes},\n      \"efficiency_pct\": {efficiency_pct},\n      \"wasted_pct\": {wasted_pct}\n    }}",
                corpus = corpus_name,
                packer = packer_label(kind),
                glyphs_total = glyphs.len() as u64,
                placed_total = placed_total,
                rejected_total = rejected_total,
                used_bytes = stats.used_bytes,
                atlas_bytes = (ATLAS_SIZE as u64) * (ATLAS_SIZE as u64),
                efficiency_pct = stats.efficiency_pct(),
                wasted_pct = stats.wasted_pct(),
            ));
        }
    }
    println!(
        "{{\n  \"$schema\": \"https://frankenterm.dev/schemas/atlas-packing/v1.json\",\n  \"_comment\": \"Per-(corpus, packer) atlas packing efficiency for ft-gtcm9.5 attestation. Generated by `cargo run --release -p frankenterm-core --example atlas_packing_attestation`. Re-run before each release; the file is sha256-hashed into the per-release attestation bundle by scripts/attestation-build.sh.\",\n  \"schema_version\": \"{schema}\",\n  \"atlas_size_px\": {atlas_size},\n  \"results\": [\n{rows}\n  ]\n}}",
        schema = SCHEMA_VERSION,
        atlas_size = ATLAS_SIZE,
        rows = entries.join(",\n"),
    );
}
