#!/usr/bin/env bash
# G51 / ft-tf6g3.39: Verify-the-verifier self-test for
# scripts/attestation-verify.sh.
#
# Drives the verifier through 10 hand-crafted fixture bundles and
# asserts on each verdict + error-pattern combination. The fixtures
# live under tests/fixtures/attestation-verify-self-test/fixtures/
# and are regenerated by running:
#
#     scripts/regenerate-attestation-verify-fixtures.sh
#
# The positive-control fixture (all_sections_present_valid.json) embeds
# sha256 hashes of upstream artifacts (docs/perf/headline-claims.json,
# docs/attestations/perf/lindley-bounds.json, etc.). When sibling agents
# update those upstream files, the fixture's recorded hashes go stale
# and the positive-control assertion starts (correctly) failing with
# "ok expected=true got=false". Regenerate via the helper script above
# and re-commit the fixtures to restore green-test state.
#
# Coverage:
#   - 1 positive control:    all_sections_present_valid.json   (ok=true)
#   - 9 tampered variants:                                     (ok=false)
#       - tampered_artifact_hash
#       - tampered_signature_canonical_hash
#       - missing_required_slot
#       - extra_unknown_slot
#       - wrong_schema_version
#       - missing_release_block
#       - inflated_taxonomy_coverage
#       - tampered_confidence_summary
#       - empty_bundle
#       - malformed_json
#
# Each tampered fixture's assertion includes a regex match on the
# expected error string so a mutation that produces the WRONG error
# kind (e.g. tampered hash flagged as a 'missing slot') still fails
# the test.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VERIFIER="${REPO_ROOT}/scripts/attestation-verify.sh"
FIX_ROOT="${REPO_ROOT}/tests/fixtures/attestation-verify-self-test/fixtures"

command -v jq >/dev/null || { echo "jq required" >&2; exit 2; }
[[ -x "$VERIFIER" ]] || { echo "$VERIFIER not executable" >&2; exit 2; }
[[ -d "$FIX_ROOT" ]] || { echo "$FIX_ROOT missing" >&2; exit 2; }

PASS=0
FAIL=0
pass() { printf 'PASS: %s\n' "$1"; PASS=$((PASS+1)); }
fail() { printf 'FAIL: %s\n  %s\n' "$1" "$2" >&2; FAIL=$((FAIL+1)); }

# Run the verifier against the named fixture and assert that
# (a) ok matches expected_ok (true | false)
# (b) at least one error string matches expected_pattern (regex)
#
# For the malformed-json / empty-bundle fixtures the verifier exits
# before emitting JSON; we accept any non-zero exit + non-empty stderr
# as a valid "verifier refused" outcome.
expect_verdict() {
  local fixture="$1" expected_ok="$2" expected_pattern="$3"
  local label="fixture=$fixture expected_ok=$expected_ok"
  local out rc
  set +e
  out=$("$VERIFIER" "$FIX_ROOT/$fixture" --json 2>&1)
  rc=$?
  set -e
  # If the verifier exited non-zero without JSON, only the malformed /
  # empty fixtures should hit this path. Accept rc != 0 + non-empty out
  # as "verifier rejected" for those.
  if ! printf '%s' "$out" | jq -e . >/dev/null 2>&1; then
    if [[ "$expected_ok" == "false" && $rc -ne 0 ]]; then
      pass "$label (verifier refused with rc=$rc)"
    else
      fail "$label" "non-JSON output and rc=$rc"
    fi
    return
  fi
  local actual_ok
  actual_ok=$(printf '%s' "$out" | jq -r 'if has("ok") then (.ok | tostring) else "null" end')
  if [[ "$actual_ok" != "$expected_ok" ]]; then
    fail "$label" "ok expected=$expected_ok got=$actual_ok"
    return
  fi
  # For ok=true cases the pattern is empty; skip the error-string check.
  if [[ -z "$expected_pattern" ]]; then
    pass "$label"
    return
  fi
  local errors_joined
  errors_joined=$(printf '%s' "$out" | jq -r '.errors // [] | join(" || ")')
  if printf '%s' "$errors_joined" | grep -qE "$expected_pattern"; then
    pass "$label (error matched /$expected_pattern/)"
  else
    fail "$label" "no error matched /$expected_pattern/; errors=$errors_joined"
  fi
}

# ---------------------------------------------------------------------------
# 1: Positive control — fresh bundle from scripts/attestation-build.sh
# ---------------------------------------------------------------------------
expect_verdict "all_sections_present_valid.json" "true" ""

# ---------------------------------------------------------------------------
# 2-10: Tampered variants
# ---------------------------------------------------------------------------
expect_verdict "tampered_artifact_hash.json"           "false" "sha256 mismatch"
expect_verdict "tampered_signature_canonical_hash.json" "false" "signature|canonical"
expect_verdict "missing_required_slot.json"            "false" "missing|required|category"
expect_verdict "extra_unknown_slot.json"               "false" "unknown|forbidden|fake"
expect_verdict "wrong_schema_version.json"             "false" "schema|version|9\\.9\\.9"
expect_verdict "missing_release_block.json"            "false" "release|version|tag"
expect_verdict "inflated_taxonomy_coverage.json"       "false" "taxonomy|coverage"
expect_verdict "tampered_confidence_summary.json"      "false" "confidence|records|summary"
expect_verdict "empty_bundle.json"                     "false" "."
expect_verdict "malformed_json.json"                   "false" "."

printf '\n---\n%d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]] || exit 1
